### ISSUE TITLE
Foreign key property isn't removed after a performed data mapping

### ISSUE THREAD

**Issue by snurra** [Oktavilla/backbone-despotism#12]
When using data mappings, the foreign key property isn't deleted afterwards. This can be a problem (or at least a peculiar side-effect) when the foreign key property is also an accepted property.

Example:

```JavaScript
props: {
  "id": Backbone.StrictModel.type.STRING,
  "remoteId": {
    "type": Backbone.StrictModel.type.STRING,
    "foreignKey": "id"
  }
}
```

Current result of setting `{ id: "xyz" }` on an empty model using data mappings: 
```
{ 
  id: "xyz", 
  remoteId: "xyz" 
}
```

What I think the result should be:
```
{ 
  remoteId: "xyz" 
}
```

**Comment by snurra** [comment]
@jsahlen @martinlissmyr 👍  or 👎 ?

**Comment by jsahlen** [comment]
Maybe a stupid question: how will you be able to set the `id` property to an actual value?

**Comment by martinlissmyr** [comment]
It makes sense to me. At the moment I can't really understand why we built it like that in the first place.

**Comment by snurra** [comment]
@jsahlen Using `{ useForeignKeys: false }`.

**Comment by snurra** [comment]
@martinlissmyr We didn't really think about the case where a foreign key could also be a local key.

**Comment by martinlissmyr** [comment]
At some point I think we should move this conversion crap out of Despotism. I think it should be done more explicitly and not on every `set`... But that's for a rainier day.

**Comment by snurra** [comment]
@martinlissmyr Agree, it's getting messy - and is also a quite different thing.

**Comment by snurra** [comment]
@martinlissmyr Actually, we sort of took a first step in that direction with the `useForeignKeys` option ~~(which is `false` by default)~~.

**Comment by snurra** [comment]
@martinlissmyr Apparently the conditions for when data mapping occurs and when it doesn't is a little bit more complex than what I suggested above: https://github.com/Oktavilla/backbone-despotism/blob/master/backbone-despotism.js#L116

**Comment by snurra** [comment]
Oh, after writing some test cases for this I realized that this already happens. I was under the false impression that it didn't, but I was mistaken. So sorry! 🙇
